Repository Honzapda/Honzapda_iOS, pull requests merged in 2024-05, with the labels that each got.

#22 [Design] 정보 더 보기 UI 구현
  Honzapda.xcodeproj/project.pbxproj
  Honzapda/Presentation/Cafe/View/Main/DetailPageMainView.swift
  Honzapda/Presentation/Cafe/View/Main/MoreHelpfulInformationView.swift
  Honzapda/Presentation/Cafe/View/Main/MoreReviewView.swift
  Honzapda/Presentation/Cafe/View/Recycle/DividerBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/InfoBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UserReviewsBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UsersHelpfulInformationBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UsersHelpfulInformationUnderbarView.swift
Labels: 💚 영훈, 🎨 Design

#26 [Fix] #22 PR 충돌 문제 해결
  Honzapda.xcodeproj/project.pbxproj
  Honzapda/Presentation/Cafe/View/Main/DetailPageMainView.swift
  Honzapda/Presentation/Cafe/View/Main/MoreHelpfulInformationView.swift
  Honzapda/Presentation/Cafe/View/Main/MoreReviewView.swift
  Honzapda/Presentation/Cafe/View/Recycle/DividerBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/InfoBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UserReviewsBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UsersHelpfulInformationBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UsersHelpfulInformationUnderbarView.swift
Labels: 💚 영훈, 🛠️ Fix

#28 [Chore] 기존 파일에 폰트 extension 적용
  Honzapda/Presentation/Cafe/View/Main/DetailPageMainView.swift
  Honzapda/Presentation/Cafe/View/Main/MoreHelpfulInformationView.swift
  Honzapda/Presentation/Cafe/View/Main/MoreReviewView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UserReviewsBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UsersHelpfulInformationBoxView.swift
  Honzapda/Presentation/Cafe/View/Recycle/UsersHelpfulInformationUnderbarView.swift
Labels: 💚 영훈, 📦 Chore

#31 [Design] 로그인 화면 UI 구현
  .gitattributes
  Honzapda.xcodeproj/project.pbxproj
  Honzapda.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Honzapda.xcodeproj/xcshareddata/xcschemes/Honzapda.xcscheme
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/background_login.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/background_login.imageset/background_login.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/icon_onboarding_autoLogin_fill.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/icon_onboarding_autoLogin_fill.imageset/icon_onboarding_autoLogin_fill.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/icon_onboarding_autoLogin_none.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/icon_onboarding_autoLogin_none.imageset/icon_onboarding_autoLogin_none.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_login_error_none.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_login_error_none.imageset/image_login_error_none.png
  Honzapda/Presentation/Onboarding/View/LoginErrorView.swift
  Honzapda/Presentation/Onboarding/View/LoginView.swift
  Honzapda/Presentation/Onboarding/View/OnboardingView.swift
  Honzapda/Presentation/Onboarding/ViewModel/LoginViewModel.swift
  Honzapda/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: 🩵 유진, 🎨 Design

#30 Design/#24 searchview UI
  Honzapda.xcodeproj/project.pbxproj
  Honzapda.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Honzapda/Global/Resources/Assets.xcassets/Search/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Search/background_search.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Search/background_search.imageset/background_search.svg
  Honzapda/Global/Resources/Assets.xcassets/Search/background_searchmain.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Search/background_searchmain.imageset/background_searchmain.svg
  Honzapda/Global/Resources/Assets.xcassets/Search/icon_chevron_left.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Search/icon_chevron_left.imageset/icon_chevron_left.svg
  Honzapda/Global/Resources/Assets.xcassets/Search/icon_search_search_fill.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Search/icon_search_search_fill.imageset/icon_search_search_fill.svg
  Honzapda/Global/Resources/Assets.xcassets/Search/icon_search_xbutton_fill.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Search/icon_search_xbutton_fill.imageset/icon_search_xbutton_fill.svg
  Honzapda/Global/Resources/Assets.xcassets/Search/logo_navigationbar.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Search/logo_navigationbar.imageset/logo_navigationbar.svg
  Honzapda/Presentation/Curation/View/CurationResultView.swift
  Honzapda/Presentation/Search/Search.swift
  Honzapda/Presentation/Search/View/nonReuse/SearchMainView.swift
  Honzapda/Presentation/Search/View/nonReuse/SearchView.swift
  Honzapda/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: 🩷 재용, 🎨 Design

#46 [Design] #37 정보 제공 UI 구현
  Honzapda.xcodeproj/project.pbxproj
  Honzapda/Presentation/Cafe/View/Main/AddReviewView.swift
  Honzapda/Presentation/Cafe/View/Main/AddUserInfoView.swift
  Honzapda/Presentation/Cafe/View/Recycle/ChoseDateView.swift
Labels: 💚 영훈, ✍️ Feat, 🎨 Design
