Repository Honzapda/Honzapda_iOS, pull requests merged in 2024-03, with the labels that each got.

#11 [Hotfix] MARK 주석 경고 오류 해결 및 Asset 중복되는 파일 삭제, whitespace rules 삭제
  .swiftlint.yml
  Honzapda/Global/Resources/Assets.xcassets/AppColor/GrayScale/Black.colorset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/AppColor/GrayScale/White.colorset/Contents.json
Labels: 🩵 유진, 🛠️ Fix, 🗑️ Delete

#12 [Design] 스플래시 및 온보딩 UI 구현
  .swiftlint.yml
  Honzapda.xcodeproj/project.pbxproj
  Honzapda/Application/HonzapdaApp.swift
  Honzapda/Global/Const/Common.swift
  Honzapda/Global/Extensions/Extension+.swift
  Honzapda/Global/Extensions/Font+.swift
  Honzapda/Global/Extensions/View+.swift
  Honzapda/Global/Resources/Assets.xcassets/LaunchImage.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/background_onboarding.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/background_onboarding.imageset/OnboardingBackground.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_mood.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_mood.imageset/image_onboarding_mood.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_plug.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_plug.imageset/image_onboarding_plug.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_seat.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_seat.imageset/image_onboarding_seat.png
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_study.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Onboarding/image_onboarding_study.imageset/image_onboarding_study.png
  Honzapda/Global/Supportings/Info.plist
  Honzapda/Honzapda.entitlements
  Honzapda/Presentation/Onboarding/Model/OnboardingCardModel.swift
  Honzapda/Presentation/Onboarding/Onboarding.swift
  Honzapda/Presentation/Onboarding/OnboardingView.swift
  Honzapda/Presentation/Onboarding/View/AppleLoginButtonView.swift
  Honzapda/Presentation/Onboarding/View/OnboardingCarouselView.swift
  Honzapda/Presentation/Onboarding/View/OnboardingView.swift
  Honzapda/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: 🩵 유진, 🎨 Design

#13 [Design] 상세페이지 메인 UI 구현
  Honzapda.xcodeproj/project.pbxproj
  Honzapda/Global/Resources/Assets.xcassets/Cafe/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_crowd_high.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_crowd_high.imageset/icon_home_crowd_high.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_crowd_low.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_crowd_low.imageset/icon_home_crowd_low.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_crowd_middle.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_crowd_middle.imageset/icon_home_crowd_middle.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_info_none.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_info_none.imageset/icon_home_info_none.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_location_fill.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_location_fill.imageset/icon_home_location_fill.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_phoneNumber_fill.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_phoneNumber_fill.imageset/icon_home_phoneNumber_fill.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_review_fill.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_review_fill.imageset/icon_home_review_fill.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_star_fill.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_star_fill.imageset/icon_home_star_fill.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_my_heart_none.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_my_heart_none.imageset/icon_my_heart_none.svg
  Honzapda/Global/Resources/Assets.xcassets/Cafe/thumbnail_cafe_detail.imageset/Contents.json
  Honzapda/Global/Resources/Assets.xcassets/Cafe/thumbnail_cafe_detail.imageset/thumbnail_cafe_detail.svg
  Honzapda/Presentation/Cafe/DetailPageMain.swift
Labels: 💚 영훈, 🎨 Design
